config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
        redirect_to action: "index"
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<section class="hero is-primary is-medium">
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
	          <%= link_to 'Main Page', root_path, class: "navbar-item" %>
	          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
	        </div>
	        <div id="navbarMenuHeroA" class="navbar-menu">
	          <div class="navbar-end">
	            <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
	          </div>
	        </div>
	      </div>
	    </nav>
	  </div>

	  <!-- Hero content: will be in the middle -->
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 class="title">
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
	</section>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-primary" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<%	content_for :page_title, "Edit Post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to post.title, post  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= post.content %>
		    </div>
		    <div class="comment-count">
		    	<span class="tag is-rounded"><%# post.comments.count %> comments</span>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>

app/views/posts/new.html.erb
<div class="container">
	<h1 class="title">New Post</h1>
	<%= simple_form_for @post do |f| %>
	<div class="field">
		<div class="control">
			<%= f.input  :title, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>
	<div class="field">
		<div class="control">
			<%= f.input  :content, input_html: { class: 'textarea'}, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>
	<%= f.button :submit, ' Create new post', class: 'button is-primary' %>
	<% end %>
</div>

app/views/posts/show.html.erb
<%	content_for :page_title, @post.title %>
<section class="section">
	<div class="container">
		<nav class="level">
			<div class="level-left">
				<p class="level-item">
					<strong>Actions</strong>
				</p>
			</div>
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit", edit_post_path(@post), class: "button" %>
				</p>
				<p class="level-item">
					<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure? "}, class:"button is-danger"%>
				</p>
			</div>
		</nav>
		<hr />

		<div class="content">
			<p><%= @post.content %></p>
		</div>
	</div>
</section>